name = "imaginethis-site"
type = "javascript"
account_id = ""
workers_dev = true
route = ""
zone_id = ""

[env.production]
vars = { ENVIRONMENT = "production" }

[build]
command = "npm run build"
cwd = "."
watch_paths = ["src/**/*.astro", "src/**/*.ts", "src/**/*.css"]

[build.upload]
format = "modules"
main = "./dist"
